version: '3.9'


services:
  
  redis-test:
    image: redis:7-alpine
    restart: always

  parking_app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
  
  celery-worker:
    build: .
    command: celery -A Parking worker -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis-test:6379/0
    
    restart: always
    depends_on:
      - redis-test

